language: java

before_install:
  - ./gradlew setupCiWorkspace

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "./build/libs/diamondtorch-.${TRAVIS_TAG}jar"
  skip_cleanup: true
  on:
    tags: true